# Generated by Django 5.1.5 on 2025-03-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimeshow',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crime_shows/'),
        ),
        migrations.AddField(
            model_name='crimeshow',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crimeshow',
            name='genre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crimeshow',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
