# Generated by Django 5.1.5 on 2025-04-01 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_shows', '0003_remove_crimeshow_trailer_url_crimeshow_added_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimeshow',
            name='added_by',
        ),
        migrations.AlterField(
            model_name='crimeshow',
            name='image',
            field=models.ImageField(upload_to='crime_show_images/'),
        ),
        migrations.AlterField(
            model_name='crimeshow',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crimeshow',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('crime_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='crime_shows.crimeshow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
